name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        # - name: Install dependencies
      #   run: npm install

      #- name: Build application
      #  run: npm run build

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo chown ec2-user:ec2-user /etc/opt
            sudo chmod u+w /etc/opt
            cd /etc/opt
            git clone git@github.com:pavelshm10/nestJs-server.git 
            pm2 start app.js
            pm2 list
